global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "application"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          namespace: "application"
          app: "application"
