name: build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: temurin
          cache: maven

      - name: Java Publish
        run: mvn -B package --file source/pom.xml

      - name: Artifact Upload
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: source/target/*.jar